version: '3'

services:
  api:
    build: .
    container_name: coursecrud-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 