version: '3'

services:
  api:
    build: .
    container_name: coursecrud-api
    volumes:
      - ./:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/sql_app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 